/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LbButton: typeof import('@littleblacky/lb-vue-ui')['LbButton']
    LbIcon: typeof import('@littleblacky/lb-vue-ui')['LbIcon']
    LbInput: typeof import('@littleblacky/lb-vue-ui')['LbInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
