/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedSkeleton: typeof import('./src/components/data/skeleton/demos/AnimatedSkeleton.vue')['default']
    Basic: typeof import('./src/components/basic/button/demos/basic.vue')['default']
    BasicUsage: typeof import('./src/components/basic/icon/demos/BasicUsage.vue')['default']
    Collapse: typeof import('./src/components/basic/splitter/demos/collapse.vue')['default']
    Common1: typeof import('./src/components/basic/container/demos/common1.vue')['default']
    Common2: typeof import('./src/components/basic/container/demos/common2.vue')['default']
    Common3: typeof import('./src/components/basic/container/demos/common3.vue')['default']
    Common4: typeof import('./src/components/basic/container/demos/common4.vue')['default']
    Common5: typeof import('./src/components/basic/container/demos/common5.vue')['default']
    Common6: typeof import('./src/components/basic/container/demos/common6.vue')['default']
    CustomRowsAndCount: typeof import('./src/components/data/skeleton/demos/CustomRowsAndCount.vue')['default']
    DifferentColors: typeof import('./src/components/basic/icon/demos/DifferentColors.vue')['default']
    DifferentSizes: typeof import('./src/components/basic/button/demos/DifferentSizes.vue')['default']
    DifferentTypes: typeof import('./src/components/basic/button/demos/DifferentTypes.vue')['default']
    DisabledState: typeof import('./src/components/basic/button/demos/DisabledState.vue')['default']
    GridAlign: typeof import('./src/components/basic/layout/demos/grid-align.vue')['default']
    GridBasic: typeof import('./src/components/basic/layout/demos/grid-basic.vue')['default']
    GridGutter: typeof import('./src/components/basic/layout/demos/grid-gutter.vue')['default']
    GridResponsive: typeof import('./src/components/basic/layout/demos/grid-responsive.vue')['default']
    IconButtons: typeof import('./src/components/basic/button/demos/IconButtons.vue')['default']
    LinkButtons: typeof import('./src/components/basic/button/demos/LinkButtons.vue')['default']
    LoadingState: typeof import('./src/components/basic/button/demos/LoadingState.vue')['default']
    MinMaxSize: typeof import('./src/components/basic/splitter/demos/min-max-size.vue')['default']
    Nested: typeof import('./src/components/basic/splitter/demos/nested.vue')['default']
    PlainButtons: typeof import('./src/components/basic/button/demos/PlainButtons.vue')['default']
    RoundAndCircle: typeof import('./src/components/basic/button/demos/RoundAndCircle.vue')['default']
    SpinEffect: typeof import('./src/components/basic/icon/demos/SpinEffect.vue')['default']
    TextButtons: typeof import('./src/components/basic/button/demos/TextButtons.vue')['default']
    Vertical: typeof import('./src/components/basic/splitter/demos/vertical.vue')['default']
  }
}

